{
  "hash": "d911ce59d7fb43ce8e0b973cee3f84a3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Poisson Regression\"\nsubtitle: \"Princeton University\"\ndate: \"2025-03-05\"\nauthor: \"KW\"\ncategories: [code, analysis]\nformat:\n  html:\n    self-contained: false\n    anchor-sections: true\n    code-tools: true\n    code-fold: true\n    fig-width: 8\n    fig-height: 4\n    code-block-bg: \"#f1f3f5\"\n    code-block-border-left: \"#31BAE9\"\n    mainfont: Source Sans Pro\n    theme: journal\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    captions: true\n    cap-location: margin\n    table-captions: true\n    tbl-cap-location: margin\n    reference-location: margin\n  pdf:\n    pdf-engine: lualatex\n    toc: false\n    number-sections: true\n    number-depth: 2\n    top-level-division: section\n    reference-location: document\n    listings: false\n    header-includes:\n      \\usepackage{marginnote, here, relsize, needspace, setspace}\n      \\def\\it{\\emph}\nexecute:\n  freeze: auto\n  echo: true\n  message: false\n  warning: false\n  fig-align: center\n  fig-width: 12\n  fig-height: 8\n  editor_options: \n  chunk_output_type: inline\n  code-overflow: wrap\n  html:\n    code-fold: true\n    code-tools: true\n---\n\n\n1.  To complete this lab:\n\n-   Load packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nlibrary(tidyverse)\nlibrary(emmeans)\nlibrary(ggeffects)\nlibrary(easystats)\nlibrary(performance)\nlibrary(knitr)\n```\n:::\n\n\n-   Download the dataset:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n\ndata <- read_delim(\"https://raw.githubusercontent.com/jgeller112/psy504-advanced-stats/main/slides/Poisson/data/2010.csv\")\n```\n:::\n\n\n2.  Conduct the analysis described in the preregistration document\n\n<!-- -->\n\na.  The number of hours per week that a person spends on the Internet (\"WWWHR\") will\\\n    be predicted by their vocabulary (\"WORDSUM\"), age (\"AGE\"), sex (\"SEX\"), religiosity\\\n    (\"RELITEN\"), political orientation (\"POLVIEWS\"), and how often they work from home\\\n    (\"WRKHOME\").\n\n-   Let's use the `naniar` package's function `replace_with_na`to clean the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(naniar)\n\ndata_pos <- data %>%\n  dplyr::select(wwwhr, wordsum, age, sex, reliten, polviews, wrkhome) %>%\nreplace_with_na(.,\n             replace = list(wwwhr = c(-1, 998, 999),\n                          wordsum = c(-1, 99),\n                          reliten = c(0, 8, 9), \n             polviews = c(0, 8, 9), \n             wrkhome = c(0,8,9), \n             age=c(0, 98, 99)))\n```\n:::\n\n\nQ: Can you explain what might be going on in the above code?\n\nA: The code is using `dplyr` package to select 7 columns, then replace the values specified in the list with NAs. For instance, it replaces `wwwhr` values -1, 998, and 999 to NAs.\n\nQ: The next step in data cleaning would be to ensure that the data in your code are aligned with the description/ usage context of the variables\n\n-   Recode sex and reliten as necessary\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos = data_pos %>%\n  mutate(age_recode = age - mean(age, na.rm=TRUE),\n         sex_recode = as.factor(sex),\n         reliten_recode = as.factor(reliten),\n         polviews_recode = as.factor(polviews),\n         wrkhome_recode = as.factor(wrkhome))\n```\n:::\n\n\n## Missingness\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos %>%\n  dplyr::select(reliten, reliten_recode)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2,044 × 2\n   reliten reliten_recode\n     <dbl> <fct>         \n 1       1 1             \n 2       4 4             \n 3       1 1             \n 4       1 1             \n 5       1 1             \n 6       4 4             \n 7       3 3             \n 8       1 1             \n 9       1 1             \n10       1 1             \n# ℹ 2,034 more rows\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(skimr)\nskimr::skim(data_pos)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |         |\n|:------------------------|:--------|\n|Name                     |data_pos |\n|Number of rows           |2044     |\n|Number of columns        |12       |\n|_______________________  |         |\n|Column type frequency:   |         |\n|factor                   |4        |\n|numeric                  |8        |\n|________________________ |         |\n|Group variables          |None     |\n\n\n**Variable type: factor**\n\n|skim_variable   | n_missing| complete_rate|ordered | n_unique|top_counts                     |\n|:---------------|---------:|-------------:|:-------|--------:|:------------------------------|\n|sex_recode      |         0|          1.00|FALSE   |        2|-1: 1153, 1: 891               |\n|reliten_recode  |        99|          0.95|FALSE   |        4|2: 747, 1: 707, 4: 363, 3: 128 |\n|polviews_recode |        71|          0.97|FALSE   |        7|4: 746, 6: 315, 5: 265, 2: 259 |\n|wrkhome_recode  |       882|          0.57|FALSE   |        6|1: 674, 5: 147, 2: 101, 4: 92  |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd|     p0|    p25|   p50|   p75|   p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|------:|------:|-----:|-----:|------:|:-----|\n|wwwhr         |       996|          0.51|  9.79| 13.41|   0.00|   2.00|  5.00| 14.00| 168.00|▇▁▁▁▁ |\n|wordsum       |       657|          0.68|  6.03|  2.07|   0.00|   5.00|  6.00|  7.00|  10.00|▁▃▇▅▂ |\n|age           |         3|          1.00| 47.97| 17.68|  18.00|  33.00| 47.00| 61.00|  89.00|▇▇▇▅▃ |\n|sex           |         0|          1.00| -0.13|  0.99|  -1.00|  -1.00| -1.00|  1.00|   1.00|▇▁▁▁▆ |\n|reliten       |        99|          0.95|  2.08|  1.08|   1.00|   1.00|  2.00|  3.00|   4.00|▇▇▁▂▃ |\n|polviews      |        71|          0.97|  4.08|  1.46|   1.00|   3.00|  4.00|  5.00|   7.00|▃▂▇▃▅ |\n|wrkhome       |       882|          0.57|  2.26|  1.72|   1.00|   1.00|  1.00|  4.00|   6.00|▇▁▁▂▁ |\n|age_recode    |         3|          1.00|  0.00| 17.68| -29.97| -14.97| -0.97| 13.03|  41.03|▇▇▇▅▃ |\n\n\n:::\n:::\n\n\n## Fit a Poisson model to the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(lme4)\nmodel1 = glm(wwwhr~age_recode+wordsum+sex_recode+reliten_recode+polviews_recode+wrkhome_recode, \n              data=data_pos,\n              family=poisson(link = \"log\"))\n```\n:::\n\n\n## Carry out model checking\n\nHint: performance package has the function you're looking for\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(performance)\nperformance::check_model(model1, check = c(\"pp_check\", \"outliers\", \"vif\", \"overdispersion\"))\n```\n\n::: {.cell-output-display}\n![](poisson_lab_questions-1_files/figure-html/unnamed-chunk-7-1.png){width=768}\n:::\n:::\n\n\n## Find any outliers\n\n\n::: {.cell}\n\n```{.r .cell-code}\noutlier_idx = check_outliers(model1)\noutlier_idx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n3 outliers detected: cases 72, 156, 363.\n- Based on the following method and threshold: cook (0.8).\n- For variable: (Whole model).\n```\n\n\n:::\n:::\n\n\n## Refit the model after excluding outliers\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_pos2 = data_pos %>%\n  filter(! row_number() %in% which(outlier_idx))\n\nmodel2 = glm(wwwhr~age+wordsum+sex_recode+reliten_recode+polviews_recode+wrkhome_recode, \n              data=data_pos2,\n              family=poisson(link=\"log\"))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(model2) %>%\n  print_html()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"qbmyjfrske\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qbmyjfrske table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qbmyjfrske thead, #qbmyjfrske tbody, #qbmyjfrske tfoot, #qbmyjfrske tr, #qbmyjfrske td, #qbmyjfrske th {\n  border-style: none;\n}\n\n#qbmyjfrske p {\n  margin: 0;\n  padding: 0;\n}\n\n#qbmyjfrske .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 100%;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qbmyjfrske .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qbmyjfrske .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qbmyjfrske .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qbmyjfrske .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qbmyjfrske .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qbmyjfrske .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qbmyjfrske .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qbmyjfrske .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qbmyjfrske .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qbmyjfrske .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qbmyjfrske .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qbmyjfrske .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qbmyjfrske .gt_row {\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qbmyjfrske .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbmyjfrske .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qbmyjfrske .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qbmyjfrske .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qbmyjfrske .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbmyjfrske .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qbmyjfrske .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbmyjfrske .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qbmyjfrske .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbmyjfrske .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qbmyjfrske .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qbmyjfrske .gt_left {\n  text-align: left;\n}\n\n#qbmyjfrske .gt_center {\n  text-align: center;\n}\n\n#qbmyjfrske .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qbmyjfrske .gt_font_normal {\n  font-weight: normal;\n}\n\n#qbmyjfrske .gt_font_bold {\n  font-weight: bold;\n}\n\n#qbmyjfrske .gt_font_italic {\n  font-style: italic;\n}\n\n#qbmyjfrske .gt_super {\n  font-size: 65%;\n}\n\n#qbmyjfrske .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qbmyjfrske .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qbmyjfrske .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qbmyjfrske .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qbmyjfrske .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qbmyjfrske .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qbmyjfrske .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#qbmyjfrske .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#qbmyjfrske div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Parameter\">Parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Coefficient\">Coefficient</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"SE\">SE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"a95%-CI\">95% CI</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"z\">z</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p\">p</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">(Intercept)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">1.89</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.09</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(1.71, 2.07)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">20.52</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">age</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.02</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">1.10e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.02, -0.01)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-15.29</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wordsum</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">7.86e-03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.08, 0.11)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">12.38</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">sex recode (1)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.22</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.03</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.17, 0.27)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">8.13</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten recode (2)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.34</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.26, 0.41)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">8.88</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten recode (3)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.43</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.30, 0.55)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">6.68</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">reliten recode (4)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.65</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.57, 0.72)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">16.23</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (2)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.10</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.23, 0.03)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-1.49</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.136 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (3)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.18</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.31, -0.04)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-2.51</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.012 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (4)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.21</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.33, -0.08)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-3.23</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.001 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (5)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.06</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.19, 0.07)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-0.92</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.359 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (6)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.25</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.07</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.39, -0.11)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-3.46</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">polviews recode (7)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">-0.31</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.10</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(-0.51, -0.11)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">-3.02</td>\n<td headers=\"p\" class=\"gt_row gt_center\">0.003 </td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome recode (2)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.21</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.12, 0.29)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">4.57</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome recode (3)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.35</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.05</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.26, 0.44)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">7.50</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome recode (4)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.44</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.35, 0.52)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">9.76</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome recode (5)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.24</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.04</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.15, 0.32)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">5.64</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n    <tr><td headers=\"Parameter\" class=\"gt_row gt_left\" style=\"border-right-width: 1px; border-right-style: solid; border-right-color: #d3d3d3;\">wrkhome recode (6)</td>\n<td headers=\"Coefficient\" class=\"gt_row gt_center\">0.40</td>\n<td headers=\"SE\" class=\"gt_row gt_center\">0.06</td>\n<td headers=\"95% CI\" class=\"gt_row gt_center\">(0.29, 0.51)</td>\n<td headers=\"z\" class=\"gt_row gt_center\">7.20</td>\n<td headers=\"p\" class=\"gt_row gt_center\">&lt; .001</td></tr>\n  </tbody>\n  <tfoot class=\"gt_sourcenotes\">\n    <tr>\n      <td class=\"gt_sourcenote\" colspan=\"6\"></td>\n    </tr>\n  </tfoot>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n### Check for Overdispersion\n\nHint: performance package has the function you're looking for\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_overdispersion(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Overdispersion test\n\n       dispersion ratio =   15.102\n  Pearson's Chi-Squared = 8804.224\n                p-value =  < 0.001\n```\n\n\n:::\n:::\n\n\nWhat do you notice? And what's a good next step forward? Can there be another model class that can fit the data? If so, fit this model to the data.\n\n-   There is overdispersion, which means there is more variation in the response than what's implied by a Poisson model. We can try to fit a negative-binomial regression model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel3 = glm.nb(wwwhr~age+wordsum+sex_recode+reliten_recode+polviews_recode+wrkhome_recode, \n              data=data_pos2)\n\nmodel4 = MASS::glm.nb(wwwhr~age+wordsum+sex_recode+reliten_recode+polviews_recode+wrkhome_recode, \n              data=data_pos2)\n```\n:::\n\n\n## Which one is better- your earlier model, or later model?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_likelihoodratio(model2, model3) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|       |Name   |Model  | df| df_diff|     Chi2|  p|\n|:------|:------|:------|--:|-------:|--------:|--:|\n|model2 |model2 |glm    | 18|      NA|       NA| NA|\n|model3 |model3 |negbin | 19|       1| 4510.038|  0|\n\n\n:::\n\n```{.r .cell-code}\ntest_likelihoodratio(model2, model4) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|       |Name   |Model  | df| df_diff|     Chi2|  p|\n|:------|:------|:------|--:|-------:|--------:|--:|\n|model2 |model2 |glm    | 18|      NA|       NA| NA|\n|model4 |model4 |negbin | 19|       1| 4510.038|  0|\n\n\n:::\n:::\n\n\nThe later model is better here, which means the previous poisson model was not a good fit to the data.\n\n## What is zero inflation? Is there zero-inflation in your chosen model?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nperformance::check_zeroinflation(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for zero-inflation\n\n   Observed zeros: 40\n  Predicted zeros: 67\n            Ratio: 1.68\n```\n\n\n:::\n:::\n\n\nThere is no zero-inflation here since \\# of observed zeros \\< \\# of predicted zeros.\n\n::: panel-tabset\n## Log Lambda\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(coef(model4))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     (Intercept)              age          wordsum      sex_recode1 \n      1.72933133      -0.01630350       0.10573220       0.14429163 \n reliten_recode2  reliten_recode3  reliten_recode4 polviews_recode2 \n      0.28114285       0.38546776       0.62578244       0.17573144 \npolviews_recode3 polviews_recode4 polviews_recode5 polviews_recode6 \n      0.09431515      -0.04193018       0.13914802      -0.04427420 \npolviews_recode7  wrkhome_recode2  wrkhome_recode3  wrkhome_recode4 \n     -0.15510946       0.11140958       0.31377893       0.30530537 \n wrkhome_recode5  wrkhome_recode6 \n      0.15257360       0.25947760 \n```\n\n\n:::\n\n```{.r .cell-code}\nprint(exp(coef(model4)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n     (Intercept)              age          wordsum      sex_recode1 \n       5.6368834        0.9838287        1.1115242        1.1552210 \n reliten_recode2  reliten_recode3  reliten_recode4 polviews_recode2 \n       1.3246428        1.4703019        1.8697083        1.1921179 \npolviews_recode3 polviews_recode4 polviews_recode5 polviews_recode6 \n       1.0989060        0.9589367        1.1492942        0.9566916 \npolviews_recode7  wrkhome_recode2  wrkhome_recode3  wrkhome_recode4 \n       0.8563214        1.1178527        1.3685871        1.3570393 \n wrkhome_recode5  wrkhome_recode6 \n       1.1648282        1.2962527 \n```\n\n\n:::\n\n```{.r .cell-code}\nmean(exp(predict(model4, type = \"link\")))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.879506\n```\n\n\n:::\n:::\n\n\n## Mean Count\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(mean(data_pos2$wwwhr, na.rm = TRUE))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 9.792543\n```\n\n\n:::\n\n```{.r .cell-code}\ndata_pos_base = data_pos2 %>%\n  filter(sex_recode==-1, reliten_recode==1, polviews_recode==1, wrkhome_recode==1)\nmean(data_pos_base$wwwhr, na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 5.4\n```\n\n\n:::\n:::\n\n:::\n\n## Report your conclusions\n\nThe coefficients of the model is roughly similar to the log value of the mean of the dependent variable. The exponential of the intercept of the model is 5.637, while the mean number of hours per week that a person spends on the internet (wwwhr) for the baseline group (sex=-1, religosity=1, political_orientation=1, work_from_home=1) is 5.4.\n\nBecause of the numerous number of levels for different categorical variables, here we don't look at each level. We can use our full model to predict the dependent variable, and then take the mean of the exponential, which is 9.880, while the mean wwwhr for the whole dataset is 9.793.\n\nOverall, a negative-binomial regression model is a good fit to the data due to dispersion. We don't need to use a zero-inflated model since there is no zero-inflation.\n",
    "supporting": [
      "poisson_lab_questions-1_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}