{
  "hash": "9366d008d8224debb3a0df2f8a5192f6",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab: Logistic Regression\"\nsubtitle: \"Princeton University\"\ndate: \"2025-02-12\"\nauthor: \"KW\"\ncategories: [code, analysis]\noutput: \n  tufte::tufte_html:\n    css: \n    tufte_variant: \"envisioned\"\n    highlight: github-dark\n    fig_height: 10\n    fig_width: 16\n    toc: true\n    toc_depth: 1\nexecute: \n  message: false\n  warning: false\nformat: \n  html:\n    code-fold: true\n    code-overflow: wrap\nengine: knitr\n---\n\n\n-   Assignment requirements:\n\n    -   If you are using Github (recommended), make sure to commit and push your work to GitHub regularly, at least after each exercise. Write short and informative commit messages, and share the link to your assignment with me. If not, you can also send me the **rmd** & **rendered file** via Canvas.\n\n    -   In this assignment, you will not need to code from scratch. Rather, you'll need to fill in code where needed. This assignment has a logisitic regression implementation for a scenario from EDA down to model comparison (and would be useful for whenever you may encounter such a situation in the future).\n\n    -   I want the assignments to begin reflecting a bit more of how you'd be doing things on your own, where you have some prior knowledge and you figure other things out (by referring to documentation, etc.) . In addition to the rmd, I also want you to submit to me **notes** of anything new that you learn while finishing the assignment. And any pain-points, and we'll discuss more.\n\n-   Note:\n\n    -   If you are fitting a model, display the model output in a neatly formatted table. (The `gt` `tidy` and `kable` functions can help!). `Modelsummary` also looks good(https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html)\n\n    -   Make sure that your plots are clearly labeled – for all axes, titles, etc.\\\n\n## Data: General Social Survey\n\nThe General Social Survey (GSS) has been used to measure trends in attitudes and behaviors in American society since 1972. In addition to collecting demographic information, the survey includes questions used to gauge attitudes about government spending priorities, confidence in institutions, lifestyle, and many other topics. A full description of the survey may be found here.\n\nThe data for this lab are from the 2016 General Social Survey. The original data set contains 2867 observations and 935 variables. We will use and abbreviated data set that includes the following variables:\n\nnatmass: Respondent’s answer to the following prompt:\n\n“We are faced with many problems in this country, none of which can be solved easily or inexpensively. I’m going to name some of these problems, and for each one I’d like you to tell me whether you think we’re spending too much money on it, too little money, or about the right amount…are we spending too much, too little, or about the right amount on mass transportation?”\n\nage: Age in years.\n\nsex: Sex recorded as male or female\n\nsei10: Socioeconomic index from 0 to 100\n\nregion: Region where interview took place\n\npolviews: Respondent’s answer to the following prompt:\n\n“We hear a lot of talk these days about liberals and conservatives. I’m going to show you a seven-point scale on which the political views that people might hold are arranged from extremely liberal - point 1 - to extremely conservative - point 7. Where would you place yourself on this scale?”\n\nThe data are in gss2016.csv in the data folder.\n\n## EDA\n\n> Let’s begin by making a binary variable for respondents’ views on spending on mass transportation. Create a new variable that is equal to “1” if a respondent said spending on mass transportation is about right and “0” otherwise. Then plot the proportion of the response variable, using informative labels for each category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(ggrepel)\nlibrary(readr)\nlibrary(tidyr)\nlibrary(knitr)\nlibrary(easystats)\nlibrary(broom)\nlibrary(emmeans)\nlibrary(marginaleffects)\nlibrary(performance)\nlibrary(arm)\nlibrary(modelsummary)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# load data\ndata <- read.csv(\"gss2016.csv\")\n```\n:::\n\n\nFill in the \"\\_\\_\\_\\_\" below to encode the binary variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n   mutate(mass_trans_spend_right = ifelse(natmass==\"About right\", 1, 0))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions\nmass_spend_summary <- data %>%\n  count(mass_trans_spend_right) %>%\n  mutate(proportion = n / sum(n))\n\n#Look at the dataframe structure. And make sure it's in a format that you can use for plotting.\n#Change structure if neederd\nmass_spend_long <- mass_spend_summary %>% mutate(opinion=\"Opinion\")\n\n#Factorise for plot\nmass_spend_long$mass_trans_spend_right <- as.factor(mass_spend_long$mass_trans_spend_right)\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\nggplot(mass_spend_long, aes(x = opinion, y = proportion, fill = mass_trans_spend_right)) +\n geom_bar(stat='identity') +\n  geom_text(aes(label=proportion),\n            vjust=ifelse(mass_spend_long$mass_trans_spend_right==0, -7, 7)\n            ) + \n  labs(x=\"Views on mass transportation spending\", y=\"Proportion\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\n\n> Recode `polviews` so it is a factor with levels that are in an order that is consistent with question on the survey. Note how the categories are spelled in the data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(polviews = factor(polviews,\n                           levels = c(\"Extremely liberal\",\"Liberal\", \"Slightly liberal\", \"Moderate\", \"Slghtly conservative\", \"Conservative\", \"Extrmly conservative\"),\n                           ordered = TRUE))\n```\n:::\n\n\n> Make a plot of the distribution of `polviews`\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Get proportions, format, and produce a plot like you did previously for \n\nmass_spend_summary <- data %>%\n  count(polviews) %>%\n  mutate(proportion = n / sum(n))\n\n#Look at the dataframe structure. And make sure it's in a format that you can use for plotting.\n#Change structure if neederd\nmass_spend_long <- mass_spend_summary %>% mutate(opinion=\"Opinion\")\n\n#Make plot\n#Hint: geom_bar lets you make stacked bar charts\nggplot(mass_spend_long, aes(x = opinion, y = proportion, fill = polviews)) +\n geom_bar(stat='identity') + \n  labs(x=\"Views on mass transportation spending\", y=\"Proportion\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n\n> Which political view occurs most frequently in this data set?\n>\n> Moderate occurs most frequently.\n\n> Make a plot displaying the relationship between satisfaction with mass transportation spending and political views. Use the plot to describe the relationship the two variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmass_spend_summary <- data %>%\n  count(polviews, mass_trans_spend_right) %>%\n  mutate(proportion = n / sum(n))\n\nmass_spend_summary$mass_trans_spend_right <- as.factor(mass_spend_summary$mass_trans_spend_right)\n\nggplot(mass_spend_summary, aes(x = polviews, y = proportion, fill = mass_trans_spend_right)) +\n geom_bar(stat='identity', position='fill') +\n  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + \n  labs(x=\"Political Views\", y=\"Satisfaction Proportion\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\nThe more conservative one's political views are the more they think the amount of spending on mass transportation is correct.\n\n-   We’d like to use age as a quantitative variable in your model; however, it is currently a character data type because some observations are coded as \"89 or older\".\n\n> Recode age so that is a numeric variable. Note: Before making the variable numeric, you will need to replace the values \"89 or older\" with a single value.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata <- data %>%\n  mutate(age = ifelse(age == \"89 or older\", 89, age), \n         age = as.numeric(age))\n```\n:::\n\n\n> Plot the frequency distribution of age.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data, aes(x = age)) +\n  geom_histogram(bins=30, fill=\"lightblue\", color=\"grey\") +\n  labs(x=\"Age\", y=\"Frequency\")\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n## Logistic regression\n\n> Let’s start by fitting a logistic regression model with just the intercept\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintercept_only_model <- glm(\n  mass_trans_spend_right ~ 1,\n  family=binomial,\n  data=data\n  ) \n\nintercept_only_model %>% \n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 0.1190594| 0.0393685|  3.024229| 0.0024927|\n\n\n:::\n:::\n\n\n> Interpret the intercept in the context of the data. You can do this by converting the $\\beta_0$ parameter out of the log-odds metric to the probability metric. Make sure to include the 95% confidence intervals. Then interpret the results in a sentence or two--what is the basic thing this probability tells us about?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nb0 <- coef(intercept_only_model) # get coef\n\nb0_transformed <- exp(b0) / (1 + exp(b0)) # logistic transform\n\nci_lower = b0 - 1.96 * 0.0393685\nci_upper = b0 + 1.96 * 0.0393685\n\n#transforming confidence intervals of coefficients into probabilities\np_lower = exp(ci_lower) / (1 + exp(ci_lower))\np_upper = exp(ci_upper) / (1 + exp(ci_upper))\n\n\nlogit_to_prob <- function(logit){\n  return(exp(logit) / (1 + exp(logit)))\n}\n\nlogit_to_prob(coef(intercept_only_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n(Intercept) \n  0.5297297 \n```\n\n\n:::\n\n```{.r .cell-code}\nlogit_to_prob(confint(intercept_only_model))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    2.5 %    97.5 % \n0.5104854 0.5489153 \n```\n\n\n:::\n:::\n\n\nInterpretation: The converted $\\beta_0$ parameter in probability is 0.5297 (95%CI \\[ 0.5105, 0.5489\\]). This probability should just be the proportion of mass_trans_spend_right = 1 in the data.\n\n> Now let's fit a model using the demographic factors - `age`,`sex`, `sei10` - to predict the odds a person is satisfied with spending on mass transportation. Make any necessary adjustments to the variables so the intercept will have a meaningful interpretation. *Neatly display the model coefficients (do not display the summary output)*\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#make sure that sex is a factor (i.e. to make sure R knows it's binary/categorical, and not continuous)\ndata = data %>%\n  mutate(sex=factor(sex, levels=c(\"Male\", \"Female\")))\n\n#fit with glm()\nm1 <- glm(\n  mass_trans_spend_right ~ 1 + age + sex + sei10,\n  family=binomial,\n  data=data\n  ) \n\n#produce tidy output of model coefficients\nm1 %>% \n  tidy() %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |   estimate| std.error| statistic|   p.value|\n|:-----------|----------:|---------:|---------:|---------:|\n|(Intercept) |  0.5697071| 0.1409061|  4.043169| 0.0000527|\n|age         | -0.0061659| 0.0022824| -2.701502| 0.0069027|\n|sexFemale   |  0.2557439| 0.0798020|  3.204732| 0.0013519|\n|sei10       | -0.0062271| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n:::\n\n\n> Consider the relationship between sex and one’s opinion about spending on mass transportation. Interpret the coefficient of sex in terms of the logs odds and OR of being satisfied with spending on mass transportation. What are the predicted probabilities for males and females on support for spending on mass transportation? Please include the 95% CIs around each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# m1 %>% \n#   tidy() %>%\n#   kable()\n\nm1 %>% \n  tidy(exponentiate = TRUE) %>%\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error| statistic|   p.value|\n|:-----------|---------:|---------:|---------:|---------:|\n|(Intercept) | 1.7677492| 0.1409061|  4.043169| 0.0000527|\n|age         | 0.9938530| 0.0022824| -2.701502| 0.0069027|\n|sexFemale   | 1.2914219| 0.0798020|  3.204732| 0.0013519|\n|sei10       | 0.9937922| 0.0016609| -3.749229| 0.0001774|\n\n\n:::\n\n```{.r .cell-code}\nbsex <- coef(m1)[\"sexFemale\"]\nstdsex = m1 %>%\n  tidy %>%\n  filter(`term` == \"sexFemale\") %>%\n  pull(`std.error`)\n\nci_lower_lo = bsex - 1.96 * stdsex\nci_upper_lo = bsex + 1.96 * stdsex\n\nci_lower_or = 1.29 - 1.96 * stdsex\nci_upper_or = 1.29 + 1.96 * stdsex\nprint(paste0(\"Increase in log odds: \", round(bsex,4), \" (95% CI [\", round(ci_lower_lo,4), \" \", round(ci_upper_lo,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Increase in log odds: 0.2557 (95% CI [0.0993 0.4122])\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste0(\"Odds ratio: \", round(exp(bsex),4), \" (95% CI [\", round(ci_lower_or,4), \" \", round(ci_upper_or,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Odds ratio: 1.2914 (95% CI [1.1336 1.4464])\"\n```\n\n\n:::\n\n```{.r .cell-code}\nemm_sex <- emmeans(m1, \"sex\", type = \"response\")\nemm_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n sex     prob     SE  df asymp.LCL asymp.UCL\n Male   0.495 0.0147 Inf     0.467     0.524\n Female 0.559 0.0133 Inf     0.533     0.585\n\nConfidence level used: 0.95 \nIntervals are back-transformed from the logit scale \n```\n\n\n:::\n:::\n\n\nIf you did this right, you'll find that being female (as compared to male) is associated with an increase in the log-odds of being satisfied with spending on mass transportation by 0.2557439 units (95% CI \\[0.09, 0.41\\]), holding all other variables constant. This equates to the odds of thinking the spending amount is right in females being 1.29 times the odds of thinking this in men (95% CI \\[1.13, 1.44\\]).\n\nThe predicted probability for females to be satisfied with spending on mass transportation is 55.9% (95% CI \\[53.3%, 58.5%\\]) and that of males is 49.5% (95% CI \\[46.7%, 52.4%\\]).\\\n\\\nVerify this.\n\n> Next, consider the relationship between age and one’s opinion about spending on mass transportation. Interpret the coefficient of age in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbage <- coef(m1)[\"age\"]\nstdage = m1 %>%\n  tidy %>%\n  filter(`term` == \"age\") %>%\n  pull(`std.error`)\n\nci_lower_lo = bage - 1.96 * stdage\nci_upper_lo = bage + 1.96 * stdage\n\nor = exp(bage)\nci_lower_or = exp(bage) - 1.96 * stdage\nci_upper_or = exp(bage) + 1.96 * stdage\n\nprint(paste0(\"Increase in log odds: \", round(bage,4), \" (95% CI [\", round(ci_lower_lo,4), \" \", round(ci_upper_lo,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Increase in log odds: -0.0062 (95% CI [-0.0106 -0.0017])\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste0(\"Odds ratio: \", round(or,4), \" (95% CI [\", round(ci_lower_or,4), \" \", round(ci_upper_or,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Odds ratio: 0.9939 (95% CI [0.9894 0.9983])\"\n```\n\n\n:::\n:::\n\n\nA one unit increase in age is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.00617 (95% CI \\[-0.0106, -0.0017\\]), holding all other variables constant. The odds ratio is 0.993853 (95% CI \\[0.9894, 0.9983\\]) which confirms the inverse relationship implied by the log-odds coefficient. Specifically, for each additional unit of age, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.993853, or approximately 0.617% per unit increase in age, holding other factors constant.\n\n> Consider the relationship between SES and one’s opinion about spending on mass transportation. Interpret the coefficient of SES in terms of the logs odds and OR of being satisfied with spending on mass transportation. Please include the 95% CIs around each estimate. ß\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbses <- coef(m1)[\"sei10\"]\nstdses = m1 %>%\n  tidy %>%\n  filter(`term` == \"sei10\") %>%\n  pull(`std.error`)\n\nci_lower_lo = bses - 1.96 * stdses\nci_upper_lo = bses + 1.96 * stdses\n\nor = exp(bses)\nci_lower_or = exp(bses) - 1.96 * stdses\nci_upper_or = exp(bses) + 1.96 * stdses\n\nprint(paste0(\"Increase in log odds: \", round(bses,4), \" (95% CI [\", round(ci_lower_lo,4), \" \", round(ci_upper_lo,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Increase in log odds: -0.0062 (95% CI [-0.0095 -0.003])\"\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(paste0(\"Odds ratio: \", round(or,4), \" (95% CI [\", round(ci_lower_or,4), \" \", round(ci_upper_or,4), \"])\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Odds ratio: 0.9938 (95% CI [0.9905 0.997])\"\n```\n\n\n:::\n:::\n\n\nA one unit increase in SES index is associated with a decrease in the log-odds of being satisfied with spending on mass transportation by 0.0062 units (95% CI \\[-0.0095, -0.003\\]), holding all other variables constant. The odds ratio is less than 1 (0.9937922), which confirms the negative relationship implied by the log-odds coefficient. Specifically, for each additional unit of SES index, the odds of being satisfied with mass transportation spending decrease by a factor of about 0.993, or approximately 0.7% per unit increase in SES index, holding other factors constant (95% CI \\[0.989, 0.998\\]).\n\n## Marginal effects\n\n-   Let's examine the results on the probability scale.\n\n> Calculate the marginal effects of sex, age, and SES on mass transportation spending. You can use the `margins` package function `margins` discussed in your textbook or you can use the `marginaleffects` package `avg_slope` `avg_comparisons` discussed in lecture. Interpret each estimate.\n\n\n::: {.cell}\n\n```{.r .cell-code}\navg_comparisons(m1, comparison = \"difference\") %>% \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term  |contrast      |   estimate| std.error| statistic|   p.value|   s.value|   conf.low|  conf.high|\n|:-----|:-------------|----------:|---------:|---------:|---------:|---------:|----------:|----------:|\n|age   |+1            | -0.0015153| 0.0005579| -2.716128| 0.0066050|  7.242217| -0.0026088| -0.0004219|\n|sei10 |+1            | -0.0015304| 0.0004039| -3.789362| 0.0001510| 12.692835| -0.0023219| -0.0007388|\n|sex   |Female - Male |  0.0630688| 0.0196461|  3.210251| 0.0013262|  9.558494|  0.0245632|  0.1015743|\n\n\n:::\n:::\n\n\n-   The marginal effect of age is -0.001515 (95% CI \\[-0.002609, -0.0004219\\]). So, for each additional unit increase of age, the probability of being satisfied with mass transportation spending decreases by approximately 0.1515 percentage points, holding other factors constant (p = 0.006605).\n\n-   The marginal effect of SES is -0.001530 (95% CI \\[-0.002322, -0.0007388\\]). For each one-unit increase in the socioeconomic index, the probability of being satisfied with mass transportation spending decreases by approximately 0.1530 percentage points, holding other variables constant (p = 0.0001510).\n\n-   The marginal effect for being female compared to male is 0.06307 (95% CI \\[0.02456, 0.1016\\]). This indicates that females are, on average, about 6.3% percentage points more likely than males to be satisfied with mass transportation spending, holding other factors constant.\n\n## Model comparison\n\n-   Now let’s see whether a person’s political views has a significant impact on their odds of being satisfied with spending on mass transportation, after accounting for the demographic factors.\n\n> Conduct a drop-in-deviance/likelihood ratio test to determine if polviews is a significant predictor of attitude towards spending on mass transportation. Name these two models `fit2` and `fit3`, respectively. Compare the two models.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit2 <- glm(\n  mass_trans_spend_right ~ 1 + age + sex + sei10,\n  family=binomial,\n  data=data\n)\n\nfit3 <- glm(\n  mass_trans_spend_right ~ 1 + age + sex + sei10 + polviews,\n  family=binomial,\n  data=data\n)\n\ntest_likelihoodratio(fit2, fit3) %>% kable()\n```\n\n::: {.cell-output-display}\n\n\n|     |Name |Model | df| df_diff|     Chi2|  p|\n|:----|:----|:-----|--:|-------:|--------:|--:|\n|fit2 |fit2 |glm   |  4|      NA|       NA| NA|\n|fit3 |fit3 |glm   | 10|       6| 63.02844|  0|\n\n\n:::\n:::\n\n\n> Is the model with polviews better than the model without?\n\n-   Yes.\n\n## Visualization\n\n-   Let’s plot the results\n\n-   We next use the model to produce visualizations:\n\n    -   Given the code below, interpet what is being plotted:\n\n        -   pol_plot : The predicted probability of being satisfied with the spending of mass transportation increases when political views become more conversative, when controlling for age, sex and SES.\n\n        -   sex_plot : The predicted probability of being satisfied with the spending of mass transportation is higher for women than for men, when controlling for sex, SES, and political views.\n\n        -   ses_plot: The predicted probability of being satisfied with the spending of mass transportation decreases when SES increases, when controlling for age, sex, and political views.\n\n    ::: callout-tip\n    -   adjust the various settings in your plot to make it look professional.\n\n    -   You can use `ggeffects` to get the predicted probabilities for these models.\n    :::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggeffects)\n\n\ncolors <- c(\"Extremely liberal\" = \"black\",\n            \"Liberal\" = \"#0e2f44\",  # Dark blue\n            \"Slightly liberal\" = \"#1d5a6c\",  # Less dark blue\n            \"Moderate\" = \"#358ca3\",  # Medium blue\n            \"Slghtly conservative\" = \"#71b9d1\",  # Light blue\n            \"Conservative\" = \"#a6dcef\",  # Lighter blue\n            \"Extrmly conservative\" = \"#d0f0fd\")  # Very light blue\n\npp_pol <- ggemmeans(fit3, terms = c(\"polviews\"))\npp_pol\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Predicted probabilities of mass_trans_spend_right\n\npolviews             | Predicted |     95% CI\n---------------------------------------------\nExtremely liberal    |      0.34 | 0.27, 0.43\nLiberal              |      0.39 | 0.34, 0.45\nSlightly liberal     |      0.49 | 0.43, 0.54\nModerate             |      0.57 | 0.53, 0.60\nSlghtly conservative |      0.55 | 0.50, 0.60\nConservative         |      0.58 | 0.53, 0.63\nExtrmly conservative |      0.66 | 0.57, 0.75\n\nAdjusted for:\n*   age = 48.90\n* sei10 = 46.07\n```\n\n\n:::\n\n```{.r .cell-code}\n# Adjusted plot with gradient colors\npol_plot <- ggplot(pp_pol, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  scale_color_manual(values = colors) +\n  theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) + \n  labs(title = \"Effect of Political Views on Satisfaction with Mass Transportation\",\n       x = \"Political Views\", y = \"Predicted Probability\",\n       color = \"Political Views\") +\n  theme_minimal()\npol_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-1.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_sex <- ggemmeans(fit3, terms = c(\"sex\"))\npp_sex\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Predicted probabilities of mass_trans_spend_right\n\nsex    | Predicted |     95% CI\n-------------------------------\nMale   |      0.48 | 0.44, 0.51\nFemale |      0.55 | 0.51, 0.58\n\nAdjusted for:\n*   age = 48.90\n* sei10 = 46.07\n```\n\n\n:::\n\n```{.r .cell-code}\nsex_plot <- ggplot(pp_sex, aes(x = x, y = predicted, color = x)) +\n  geom_point(size = 2) +\n  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +\n  labs(title = \"Effect of Sex on Satisfaction with Mass Transportation\",\n       x = \"Sex\", y = \"Predicted Probability\",\n       color = \"Sex\") +\n  theme_minimal()\n\nsex_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-2.png){width=1152}\n:::\n\n```{.r .cell-code}\npp_ses <- ggemmeans(fit3, terms = \"sei10\")\npp_ses\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Predicted probabilities of mass_trans_spend_right\n\nsei10 | Predicted |     95% CI\n------------------------------\n    0 |      0.57 | 0.52, 0.61\n   15 |      0.55 | 0.51, 0.58\n   25 |      0.54 | 0.51, 0.57\n   35 |      0.52 | 0.50, 0.55\n   50 |      0.51 | 0.48, 0.53\n   65 |      0.49 | 0.46, 0.52\n   75 |      0.48 | 0.44, 0.51\n  100 |      0.45 | 0.40, 0.50\n\nAdjusted for:\n* age = 48.90\n```\n\n\n:::\n\n```{.r .cell-code}\nses_plot <-  ggplot(pp_ses, aes(x = x, y = predicted)) +\n  geom_line(color = \"#2c7fb8\", size = 1) + \n  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), fill = \"#2c7fb8\", alpha = 0.2) +  # Add a confidence interval band\n  labs(title = \"Effect of SES on Satisfaction with Mass Transportation\",\n       x = \"Socioeconomic Status\", y = \"Predicted Probability\") +\n  theme_minimal() +\n  theme(legend.position = \"none\")  \nses_plot\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-18-3.png){width=1152}\n:::\n:::\n\n\n## Model Assumptions\n\n-   Is the logistic model a good choice for this data?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 86% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2) %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\nAnswer: It seems like the model does not fit the data very well. About 86% of the residuals are inside the error bounds, as opposed to the ideal \\>= 95%.\n:::\n\n## Model fit\n\n-   Calculate the $R^2$ for this model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2_mcfadden(fit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Generalized Linear Regression\n       R2: 0.010\n  adj. R2: 0.009\n```\n\n\n:::\n:::\n\n\n> R2 interpretation: The model explains around 1% of the variance in the dependent variable, which means it is not a good fit.\n>\n> Next, Take a look at the binned residual plots for each continuous predictor variable and look at linearity. Is there a predictor that sticks out? What can we do to improve model fit in this case?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: About 88% of the residuals are inside the error bounds (~95% or higher would be good).\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nOk: About 98% of the residuals are inside the error bounds.\n```\n\n\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"sei10\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbinned_residuals(fit2, term=\"age\") %>% plot(show_dots=TRUE)\n```\n\n::: {.cell-output-display}\n![](Lab-Logistic-Q_files/figure-html/unnamed-chunk-21-2.png){width=672}\n:::\n:::\n\n\n::: callout-note\nHere SES seems to stick out. For SES, only 88% of the residuals are inside the error bounds while for age, about 98% of the residuals are inside the error bounds. However, for the binned residual plot, it looks like there is no systematic trends, so I think it's reasonable to assume linearity. If we want, we can transform SES or add interaction terms to improve model fit.\n:::\n\n## Testing Polviews\n\n\n::: {.cell}\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                   estimate        SE  df z.ratio\n Extremely liberal - Moderate             -0.9266262 0.1950664 Inf  -4.750\n Extremely liberal - Slghtly conservative -0.8487137 0.2127293 Inf  -3.990\n Extremely liberal - Conservative         -0.9935486 0.2108369 Inf  -4.712\n Extremely liberal - Extrmly conservative -1.3402621 0.2792876 Inf  -4.799\n Liberal - Moderate                       -0.7090022 0.1308520 Inf  -5.418\n Liberal - Slghtly conservative           -0.6310897 0.1555805 Inf  -4.056\n Liberal - Conservative                   -0.7759246 0.1532081 Inf  -5.065\n Liberal - Extrmly conservative           -1.1226380 0.2392048 Inf  -4.693\n Slightly liberal - Extrmly conservative  -0.7334002 0.2412625 Inf  -3.040\n p.value\n  <.0001\n  0.0013\n  0.0001\n  <.0001\n  <.0001\n  0.0010\n  <.0001\n  0.0001\n  0.0382\n\nResults are averaged over the levels of: sex \nResults are given on the log odds ratio (not the response) scale. \nP value adjustment: tukey method for comparing a family of 7 estimates \n```\n\n\n:::\n\n```{.r .cell-code}\nemmeans(fit3, \"polviews\", type=\"response\") %>% pairs() %>% as.data.frame() %>% filter(p.value < .05)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n contrast                                 odds.ratio         SE  df null\n Extremely liberal / Moderate              0.3958871 0.07722426 Inf    1\n Extremely liberal / Slghtly conservative  0.4279651 0.09104070 Inf    1\n Extremely liberal / Conservative          0.3702605 0.07806458 Inf    1\n Extremely liberal / Extrmly conservative  0.2617771 0.07311109 Inf    1\n Liberal / Moderate                        0.4921350 0.06439684 Inf    1\n Liberal / Slghtly conservative            0.5320118 0.08277063 Inf    1\n Liberal / Conservative                    0.4602780 0.07051835 Inf    1\n Liberal / Extrmly conservative            0.3254202 0.07784206 Inf    1\n Slightly liberal / Extrmly conservative   0.4802732 0.11587191 Inf    1\n z.ratio p.value\n  -4.750  <.0001\n  -3.990  0.0013\n  -4.712  0.0001\n  -4.799  <.0001\n  -5.418  <.0001\n  -4.056  0.0010\n  -5.065  <.0001\n  -4.693  0.0001\n  -3.040  0.0382\n\nResults are averaged over the levels of: sex \nP value adjustment: tukey method for comparing a family of 7 estimates \nTests are performed on the log odds ratio scale \n```\n\n\n:::\n:::\n\n\n-   Conservatives are 2.7008 and 2.1726 times more likely to support mass transit spending compared to extremely liberal and liberal\n\n-   Extreme liberals are 0.3703, 0.3959, and 0.4280 times more likely to support spending compared to conservatives, moderates and slight conservatives\n\n-   Extrm conservatives are 3.8200 and 2.0821 times more likely to support mass spending than liberals and slight liberals\n\n-   Liberals are 0.4921 and 0.5320 times more likely to support spending than moderates and slight conservatives.\n\n## Conclusion\n\nBased on the model summary below, and the three figures, we conclude that age, sex, SES, and political views are all significant variables in predicting satisfaction of mass transit spending. Specifically, people that are younger tend to be more satisfied with mass transit spending; females are more satisfied with mass transit spending than males in general; people of lower socioeconomic status are more satisfied with mass transit spending; and people with more conservative political views are more satisfied with mass transit spending.\n\n\n\n|         | Df|  Deviance| Resid. Df| Resid. Dev|  Pr(>Chi)|\n|:--------|--:|---------:|---------:|----------:|---------:|\n|NULL     | NA|        NA|      2589|   3581.340|        NA|\n|age      |  1|  9.268443|      2588|   3572.072| 0.0023314|\n|sex      |  1| 12.156624|      2587|   3559.915| 0.0004891|\n|sei10    |  1| 14.119078|      2586|   3545.796| 0.0001716|\n|polviews |  6| 63.028441|      2580|   3482.768| 0.0000000|\n\n\n\nTable 1\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 1: Effect of Sex on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-sexviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 2: Effect of SES  on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-sesviews-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![Figure 3: Effect of Political Views on Satisfaction with Mass Transportation](Lab-Logistic-Q_files/figure-html/plot-polviews-1.png){width=672}\n:::\n:::\n",
    "supporting": [
      "Lab-Logistic-Q_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}